parameters:
  - name: 'platform'
    type: string

steps:
  - script: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda env create --file environment-dev.yml
    displayName: Install dependencies

  - script: |
      source activate {{cookiecutter.conda_package_name}}
      conda install gcc_linux-64=7.5.0 gcc_impl_linux-64=7.5.0 gxx_linux-64=7.5.0 gxx_impl_linux-64 -c conda-forge;
    {% raw %}
    condition: eq('${{ parameters.platform }}', 'Linux')
    {% endraw %}
    displayName: Install conda-forge compilers

  - script: |
      source activate {{cookiecutter.conda_package_name}}
      mkdir build
      cd build
      if [[ $(use_shared_{{cookiecutter.cmake_var_prefix|lower}}) == '0' ]]; then
        CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -D{{cookiecutter.cmake_var_prefix}}_BUILD_SHARED=OFF -D{{cookiecutter.cmake_var_prefix}}_USE_SHARED_{{cookiecutter.cmake_var_prefix}}=OFF";
      fi
      if [[ $(use_shared_xeus) == '0' ]]; then
        CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -D{{cookiecutter.cmake_var_prefix}}_USE_SHARED_XEUS=OFF";
      fi
      # The xeus conda package is built with CMAKE_CXX_STANDARD={{cookiecutter.cpp_standart}}
      CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DCMAKE_CXX_STANDARD={{cookiecutter.cpp_standart}}";
      cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_PREFIX_PATH=$CONDA_PREFIX -D CMAKE_INSTALL_PREFIX=$CONDA_PREFIX -D{{cookiecutter.cmake_var_prefix}}_DOWNLOAD_GTEST=ON  -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ${CMAKE_EXTRA_ARGS} $(Build.SourcesDirectory)
    displayName: Configure {{cookiecutter.package_name}}
    workingDirectory: $(Build.BinariesDirectory)

  - script: |
      source activate {{cookiecutter.conda_package_name}}
      make install -j2
    displayName: Build xeus-lua
    workingDirectory: $(Build.BinariesDirectory)/build


  # - script: |
  #     source activate {{cookiecutter.conda_package_name}}
  #     pytest . -vvv
  #   displayName: Test xeus-lua (Python)
  #   workingDirectory: $(Build.sourcesDirectory)/test
